config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'tags/index'
  end
  # TOPページ
  root to: 'public/homes#top'

  # ---会員側---
  # devise機能
  devise_for :members , controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :member do
    # ゲストログイン
    post '/member/guest_sign_in' => 'public/sessions#new_guest'
  end

  scope module: :public do
    # members
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    get "members/:id/unsubscribe" => 'members#unsubscribe', as: 'members_unsubscribe'
    # writings
    resources :writings do
      # get 'download'
      resource :writing_likes, only: [:create, :destroy]
      resources :writing_comments, only: [:create, :destroy]
    end
     # search(key_word)
    get 'search' => 'writings#word_search'
    # tags
    resources :tags do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end

  end
  # ------
  # ------

  # ---管理者側---
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # members
    resources :members, only: [:index, :show, :edit, :update]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    # writings
    resources :writings, only: [:index, :show, :update] do
      resources :writing_comments, only: [:destroy]
    end
    #  writing_comments
    resources :writing_comments, only: [:index]
    # search(key_word)
    get 'search' => 'writings#word_search'
    resources :tags, only: [:index, :edit, :create, :update, :destroy] do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end
  end
  # ------

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # --- Devise機能 ---
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  #-----------------

  # --- association　---
  has_many :writings, dependent: :destroy
  has_many :writing_comments, dependent: :destroy
  has_many :writing_likes, dependent: :destroy
  #-----------------

  # --- validation ---
  validates :name, presence: true, length: { minimum: 1, maximum: 10 }
  #-----------------

  # --- Active Storage ---
  has_one_attached :profile_image
  #-----------------

  # --- scope ---
  # 退会ユーザーは非表示
  scope :active, -> { where(is_deleted: false) }
  #-----------------

  # --- カスタムメソッド ---
  # ゲストログイン
  def self.guest
    find_or_create_by(email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "ゲストプレイヤー"
    end
  end

  # 最終ログイン日
  def last_sign_in_date
    self[:last_sign_in_at].strftime("%Y/%m/%d")
  end

  # プロファイル画像のサイズ変更
  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # いいね総数
  def total_likes
    writings.joins(:writing_likes).count
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  # ログイン確認
  before_action :authenticate_admin!

  def index
    @members = Member.order(created_at: :desc).page(params[:page])
  end

  def show
    @member = Member.find(params[:id])
    @writings = @member.writings.order(created_at: :desc).limit(5)
    @like_writings = @member.writing_likes.order(created_at: :desc).limit(5).map(&:writing)
  end

  def edit
    @member = Member.find(params[:id])
  end

  def writings
    @member = Member.find(params[:id])
    @writings = @member.writings.order(created_at: :desc).page(params[:page])
  end

  def like_writings
    @member = Member.find(params[:id])
    @like_writings = @member.writing_likes.order(created_at: :desc).map(&:writing)
    @like_writings = Kaminari.paginate_array(@like_writings).page(params[:page])
  end

  def update
    @member = Member.find(params[:id])
      if @member.update!(member_params)
        flash[:notice] = "プロフィールを変更しました"
        redirect_to admin_member_path(@member.id)
      else
        flash[:alert] = "プロフィールの変更に失敗しました"
        render :edit
      end
  end

  private

  def member_params
    params.require(:member).permit(:name, :email, :introduction, :favorite_trpg, :profile_image, :is_deleted)
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/_list.html.erb
<div class="table-responsive px-1 shadow-sm">
  <table class="table w-100">
    <thead class="">
      <tr class="text-center text-nowrap">
        <th colspan="2" style="width: 37.5%" class="px-0">タイトル</th>
        <th style="width: 8.5%" class="px-0">人数</th>
        <th style="width: 9%" class="px-0">時間</th>
        <th style="width: 8%" class="px-0">難しさ</th>
        <th style="width: 7%" class="px-0">いいね！</th>
        <th style="width: 10.5%" class="px-0">タグ</th>
        <th style="width: 10%" class="px-0">公開ステータス</th>
        <th style="width: 9.5%" class="px-0">更新日</th>
      </tr>
    </thead>
    <% writings.each do |writings| %>
      <tbody class="text-nowrap">
        <tr>
          <td style="width: 7.5%">
            <%= link_to admin_writing_path(writings.id) do %>
              <%= image_tag writings.get_thumbnail_image(60,60), class:"border shadow-sm" %></br>
            <% end %>
          </td>
          <td class="align-middle ps-0">
            <span class="fw-light small">
              <%= writings.writing_type ? '【シナリオ】' : '【ルール】' %><%= truncate("#{writings.trpg_rule.title}", length: 20) %></br>
            </span>
            <%= link_to admin_writing_path(writings.id) do %>
              <span class="ps-2">
                <%= truncate("#{writings.title}", length: 20) %>
              </span>
            <% end %>
          </td>
          <td class="align-middle text-center px-1">
              <%= writings.min_players %> ~ <%= writings.max_players %><small>人</small>
          </td>
          <td class="align-middle text-center px-1">
              <%= writings.min_play_time %> ~ <%= writings.max_play_time %><small>時間</small>
          </td>
          <td class="align-middle text-center px-1">
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= writings.getPercent(writings.difficulty) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
          </td>
          <td class="align-middle text-center">
              <%= writings.writing_likes.count %>
          </td>
          <td class="align-middle pe-1">
            <% writings.tags.each do |list| %>
              <%= list.tag_name %><br>
            <% end %>
          </td>
          <td class="align-middle text-center">
            <% if writings.is_public %>
              <span class="text-success fw-bold">公開中</span>
            <% else %>
              <span class="text-danger fw-bold">非公開</span>
            <% end %>
          </td>
          <td class="align-middle text-center px-0">
            <%= writings.updated_at.strftime('%Y/%m/%d') %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/admin/members/edit.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-10 col-12">
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2">
      <h1>プロフィールを編集</h1>
    </div>
    <%= form_with model: @member, url: admin_member_path(@member.id), method: :patch do |f| %>
    <div class="row my-3 mx-md-5 mx-0 double-border">
      <div class="mb-3">
        <%= image_tag @member.get_profile_image(100,100), class: "border rounded-circle me-4" %>
        <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*", class: "", id: "" %>
      </div>
      <div class="mb-3">
        <label for="inputName" class="form-label">ニックネーム</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ニックネーム", class: "form-control" %>
      </div>
      <div class="mb-3">
        <label for="email" class="form-label">メールアドレス</label>
        <%= f.email_field :email, id:"email", placeholder:"sample@sample.com", class: "form-control" %>
      </div>
      <div class="mb-3">
        <label for="inputIntroduction" class="form-label">自己紹介</label>
        <%= f.text_area :introduction, id:"inputIntroduction", placeholder:"よろしくお願いします！", class: "form-control" %>
      </div>
      <div class="mb-3">
        <label for="inputFavoriteTrpg" class="form-label">好きなTRPG</label>
        <%= f.text_field :favorite_trpg, id:"inputFavoriteTrpg", placeholder:"好きなTRPG", class: "form-control" %>
      </div>
      <div class="d-flex mb-3">
        <label for="inputIsDeleted" class="col-form-label mb-0 me-2">アカウント状況</label>
        <div class="col-auto">
          <%= f.select :is_deleted, {"利用中" => false, "利用停止" => true},{}, class: "form-select", id: "inputIsDeleted" %>
        </div>
      </div>
    </div>
    <div class="row my-3 mx-sm-5 mx-0 justify-content-between">
      <div class="col-sm-auto col-6 pe-0 ms-auto text-end">
        <%= f.submit "変更を保存", class: "btn btn-outline-primary fw-bold" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/members/index.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <div class="row my-3 mx-0 border-bottom border-dark border-2">
      <h1>メンバーリスト</h1>
    </div>
    <div class="row mx-0 mb-3">
      <div class="table-responsive px-1 shadow-sm">
        <table class="table table-sm table-bordered">
          <thead>
            <tr class="text-center text-nowrap">
              <th colspan="2" style="width: 33%">メンバー名</th>
              <th style="width: 40% max-width: 40%" class="px-5">好きなTRPG</th>
              <th style="width: 7%">いいね！</th>
              <th style="width: 10%">公開ステータス</th>
              <th style="width: 10%">最終ログイン日</th>
            </tr>
          </thead>
          <% @members.each do |member| %>
          <tbody>
            <tr>
              <td rowspan="2" style="width: 5%" class="align-middle">
                <div class="text-center">
                  <%= link_to admin_member_path(member.id) do %>
                    <%= image_tag member.get_profile_image(60,60), class: "border rounded-circle shadow-sm" %>
                  <% end %>
                </div>
              </td>
              <td>
                <%= link_to admin_member_path(member.id), class: "link-dark text-decoration-none" do %>
                  <%= member.name %>
                <% end %>
              </td>
              <td rowspan="2" class="align-middl">
                <div class="w-100 wh-100" style="min-width: 300px; height: 71px;">
                <%= truncate("#{member.favorite_trpg}", length: 90) %>
                </div>
              </td>
              <td rowspan="2" class="align-middle">
                <div class="text-center">
                  <%= member.total_likes %>
                </div>
              </td>
              <td rowspan="2" class="align-middle">
                <div class="text-center">
                  <% if member.is_deleted %>
                    <span class="text-danger fw-bold">利用停止</span>
                  <% else %>
                    <span class="text-success fw-bold">利用中</span>
                  <% end %>
                </div>
              </td>
              <td rowspan="2" class="align-middle">
                <div class="text-center">
                  <%= member.last_sign_in_date %>
                </div>
              </td>
            </tr>
            <tr>
              <td class="text-nowrap">
                <%= truncate("#{member.introduction}", length: 30) %>
              </td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= paginate(@members) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/like_writings.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2">
      <h1>メンバー情報</h1>
    </div>
    <div class="row mb-5 mx-md-5 mx-0">
      <div class="col-sm-3 col-12 pt-3">
        <div class="row justify-content-center">
          <div class="col-sm-12 col-auto">
            <div class="text-center mb-1">
              <%= image_tag @member.get_profile_image(100,100), class:"border rounded-circle" %>
            </div>
          </div>
          <div class="col-sm-12 col-auto my-3 px-sm-3 px-0">
            <p class="text-center m-1">
              <span class="p-1 border rounded-circle"><i class="fa-solid fa-heart fa-lg heart-color"></i></span>
              <br class="d-xxl-none d-none d-sm-inline">いいねされた回数：<%= @member.total_likes %>
          　</p>
          </div>
        </div>
      </div>
      <div class="col-sm-9 col-12">
        <div class="row double-border">
          <p>
            <span class="small"><ニックネーム></span></br>
            <%= "#{@member.name}" %>
          </p>
          <p>
            <span class="small"><自己紹介></span></br>
            <%= @member.introduction %>
          </p>
          <p class="mb-3">
            <span class="small"><好きなTRPG></span></br>
            <%= @member.favorite_trpg %>
          </p>
          <p class="mb-3">アカウント状況：
            <% if @member.is_deleted %>
              <span class="text-danger fw-bold">利用停止</span>
            <% else %>
              <span class="text-success fw-bold">利用中</span>
            <% end %>
          </p>
          <p class="mb-0 text-end">
            <i class="fa-regular fa-clock"></i>
            最終ログイン日：
            <%= @member.last_sign_in_date %>
          </p>
        </div>
        <div class="row my-2 justify-content-end">
          <div class="d-grid col-sm-auto col-12 pe-sm-0 px-0 text-end">
            <%= link_to "プロフィール編集", edit_admin_member_path(@member.id), class:"btn btn-outline-primary fw-bold" %>
          </div>
        </div>
      </div>
    </div>
    <!-- お気に入りの作品一覧 -->
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2">
      <h2>いいねした作品</h2>
    </div>
    <div class="row justify-content-sm-between justify-content-center mx-md-5 mx-0 mb-2">
      <div class="col-auto">
        <%= link_to "<< メンバー情報に戻る", admin_member_path(@member.id) %>
      </div>
      <div class="col-auto">
        <%= link_to "その他投稿した作品一覧 >>", admin_member_writings_path(@member.id) %>
      </div>
    </div>
    <div class="row mx-md-5 mx-0 mb-3">
      <%= render 'admin/writings/list', writings: @like_writings %>
    </div>
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= paginate(@like_writings) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2">
      <h1>メンバー情報</h1>
    </div>
    <div class="row mb-5 mx-md-5 mx-0">
      <div class="col-sm-3 col-12 pt-3">
        <div class="row justify-content-center">
          <div class="col-sm-12 col-auto">
            <div class="text-center mb-1">
              <%= image_tag @member.get_profile_image(100,100), class:"border rounded-circle" %>
            </div>
          </div>
          <div class="col-sm-12 col-auto my-3 px-sm-3 px-0">
            <p class="text-center m-1">
              <span class="p-1 border rounded-circle"><i class="fa-solid fa-heart fa-lg heart-color"></i></span>
              <br class="d-xxl-none d-none d-sm-inline">いいねされた回数：<%= @member.total_likes %>
            </p>
          </div>
        </div>
      </div>
      <div class="col-sm-9 col-12">
        <div class="row double-border text-break">
          <p>
            <small><ニックネーム></small></br>
            <%= @member.name %>
          </p>
          <p>
            <small><自己紹介></small></br>
            <%= safe_join(@member.introduction.split("\n"),tag(:br)) %>
          </p>
          <p class="mb-3">
            <small><好きなTRPG></small></br>
            <%= @member.favorite_trpg %>
          </p>
          <p class="mb-3">アカウント状況：
            <% if @member.is_deleted %>
              <span class="text-danger fw-bold">利用停止</span>
            <% else %>
              <span class="text-success fw-bold">利用中</span>
            <% end %>
          </p>
          <p class="mb-0 text-end">
            <i class="fa-regular fa-clock"></i>
            最終ログイン日：
            <%= @member.last_sign_in_date %>
          </p>
        </div>
        <div class="row my-2 justify-content-end">
          <div class="d-grid col-sm-auto col-12 pe-sm-0 px-0 text-end">
            <%= link_to "プロフィール編集", edit_admin_member_path(@member.id), class:"btn btn-outline-primary fw-bold" %>
          </div>
        </div>
      </div>
    </div>
    <!-- 投稿作品一覧 -->
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2" id="member_writings">
      <h2>投稿作品</h2>
    </div>
    <div class="row justify-content-end mx-md-5 mx-0 mb-2">
      <div class="col-auto">
        <%= link_to "その他投稿した作品一覧 >>", admin_member_writings_path(@member.id) %>
      </div>
    </div>
    <div class="row mx-md-5 mx-0 mb-5">
      <%= render 'list', writings: @writings %>
    </div>
    <!-- お気に入りの作品一覧 -->
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2">
      <h2>いいねした作品</h2>
    </div>
    <div class="row justify-content-end mx-md-5 mx-0 mb-2">
      <div class="col-auto">
        <%= link_to "その他いいねした作品一覧 >>", admin_member_like_writings_path(@member.id) %>
      </div>
    </div>
    <div class="row mx-md-5 mx-0 mb-5">
      <%= render 'admin/writings/list', writings: @like_writings %>
    </div>
  </div>
</div>

app/views/admin/members/writings.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2">
      <h1>メンバー情報</h1>
    </div>
    <div class="row mb-5 mx-md-5 mx-0">
      <div class="col-sm-3 col-12 pt-3">
        <div class="row justify-content-center">
          <div class="col-sm-12 col-auto">
            <div class="text-center mb-1">
              <%= image_tag @member.get_profile_image(100,100), class:"border rounded-circle" %>
            </div>
          </div>
          <div class="col-sm-12 col-auto my-3 px-sm-3 px-0">
            <p class="text-center m-1">
              <span class="p-1 border rounded-circle"><i class="fa-solid fa-heart fa-lg heart-color"></i></span>
              <br class="d-xxl-none d-none d-sm-inline">いいねされた回数：<%= @member.total_likes %>
          　</p>
          </div>
        </div>
      </div>
      <div class="col-sm-9 col-12">
        <div class="row double-border">
          <p>
            <span class="small"><ニックネーム></span></br>
            <%= "#{@member.name}" %>
          </p>
          <p>
            <span class="small"><自己紹介></span></br>
            <%= @member.introduction %>
          </p>
          <p class="mb-3">
            <span class="small"><好きなTRPG></span></br>
            <%= @member.favorite_trpg %>
          </p>
          <p class="mb-3">アカウント状況：
            <% if @member.is_deleted %>
              <span class="text-danger fw-bold">利用停止</span>
            <% else %>
              <span class="text-success fw-bold">利用中</span>
            <% end %>
          </p>
          <p class="mb-0 text-end">
            <i class="fa-regular fa-clock"></i>
            最終ログイン日：
            <%= @member.last_sign_in_date %>
          </p>
        </div>
        <div class="row my-2 justify-content-end">
          <div class="d-grid col-sm-auto col-12 pe-sm-0 px-0 text-end">
            <%= link_to "プロフィール編集", edit_admin_member_path(@member.id), class:"btn btn-outline-primary fw-bold" %>
          </div>
        </div>
      </div>
    </div>
    <!-- 投稿作品 -->
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2" id="member_writings">
      <h2>投稿作品</h2>
    </div>
    <div class="row justify-content-sm-between justify-content-center mx-md-5 mx-0 mb-2">
      <div class="col-auto">
        <%= link_to "<< メンバー情報に戻る", admin_member_path(@member.id) %>
      </div>
      <div class="col-auto">
        <%= link_to "その他いいねした作品一覧 >>", admin_member_like_writings_path(@member.id) %>
      </div>
    </div>
    <div class="row mx-md-5 mx-0 mb-3">
      <%= render 'list', writings: @writings %>
    </div>
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= paginate(@writings) %>
      </div>
    </div>
  </div>
</div>