config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'tags/index'
  end
  # TOPページ
  root to: 'public/homes#top'

  # ---会員側---
  # devise機能
  devise_for :members , controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :member do
    # ゲストログイン
    post '/member/guest_sign_in' => 'public/sessions#new_guest'
  end

  scope module: :public do
    # members
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    get "members/:id/unsubscribe" => 'members#unsubscribe', as: 'members_unsubscribe'
    # writings
    resources :writings do
      # get 'download'
      resource :writing_likes, only: [:create, :destroy]
      resources :writing_comments, only: [:create, :destroy]
    end
     # search(key_word)
    get 'search' => 'writings#word_search'
    # tags
    resources :tags do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end

  end
  # ------
  # ------

  # ---管理者側---
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # members
    resources :members, only: [:index, :show, :edit, :update]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    # writings
    resources :writings, only: [:index, :show, :update] do
      resources :writing_comments, only: [:destroy]
    end
    #  writing_comments
    resources :writing_comments, only: [:index]
    # search(key_word)
    get 'search' => 'writings#word_search'
    resources :tags, only: [:index, :edit, :create, :update, :destroy] do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end
  end
  # ------

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  # --- association ---
  has_many :writing_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :writings, through: :writing_tags
  # ------
  # --- vallidates ---
  validates :tag_name, uniqueness: true, presence: true
  # ------
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  def index
    @tag = Tag.new
    @tags = Tag.all
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag =Tag.new(tag_params)
    @tag.admin_created = true
    if @tag.save!
      flash[:notice] = "タグを新しく投稿しました。"
      redirect_to admin_tags_path
    else
      @tag = Tag.new
      @tags = Tag.all
      flash[:notice] = "タグ投稿に失敗しました。"
      render :index
    end
  end

  def update
    @tag =Tag.find(params[:id])
    if @tag.update!(tag_params)
      flash[:notice] = "タグを更新しました。"
      redirect_to admin_tags_path
    else
      @tag = Tag.find(params[:id])
      flash[:notice] = "タグの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    if @tag.destroy
      flash[:notice] = "タグを削除しました。"
      redirect_to admin_tags_path
    else
      @tag = Tag.new
      @tags =Tag.all
      flash[:notice] = "タグの削除に失敗しました。"
      render :index
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<!--admin/tags/editページ-->
<div class="row my-5 justify-content-center">
  <div class="col-11">
  <div>
    <div class="row my-3 border-bottom border-dark border-2">
      <h1 class="">タグ編集</h1>
    </div>

  <!-- タグ編集 -->
  <%= form_with model: @tag, url: admin_tag_path(@tag.id), method: :patch, local: true do |f| %>
    <div class="row form-group mx-2 mb-5">
      <div class="col-sm-auto col-12 float-start pe-sm-3 px-0">
        <label class="col-form-label">タグ名</label>
      </div>
      <div class="col-sm-auto col-12 float-start pe-sm-3 px-0">
        <%= f.text_field :tag_name, autofocus: true, :placeholder => "タグ名", class: "form-control" %>
      </div>
      <%= f.submit  "更新して保存", class: "col-sm-auto col-12 float-start btn btn-success mt-sm-0 mt-3" %>
    </div>
  <% end %>
  </div>
</div>

app/views/admin/tags/index.html.erb
<!--admin/tags/indexページ-->
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <div class="row my-3 mx-0 border-bottom border-dark border-2">
      <h1>タグ新規作成</h1>
    </div>
    <!-- 新規登録 -->
    <%= form_with model: @tag, url: admin_tags_path, method: :post do |f| %>
      <div class="row form-group mx-2 mb-5">
        <div class="col-sm-auto col-12 float-start pe-sm-3 px-0">
          <label class="col-form-label">タグ名</label>
        </div>
        <div class="col-sm-auto col-12 float-start pe-sm-3 px-0">
          <%= f.text_field :tag_name, autofocus: true, :placeholder => "タグ名", class: "form-control" %>
          <%= f.hidden_field :admin_created, :value => true %>
        </div>
        <%= f.submit "新規登録", class: "col-sm-auto col-12 btn btn-success mt-sm-0 mt-3"%>
      </div>
    <% end %>
    <!-- 一覧 -->
    <div class="row my-3 mx-0 border-bottom border-dark border-2">
      <h1>タグ一覧</h1>
    </div>
    <div class="row mx-0">
      <div class="col-xl-4 col-md-6 col-12">
        <div class="row border-bottom">
          <div class="col-5 pe-xl-0 px-lg-3 pe-md-0">
            <p>タグ名<br class="d-sm-none d-inline"><small>(タグ使用数)</small></p>
          </div>
          <div class="col-3 d-flex align-items-center justify-content-center text-center px-0">
            <p>作成区分</p>
          </div>
          <div class="col-4 d-flex align-items-center justify-content-center text-center px-0">
            <p>編集・削除</p>
          </div>
        </div>
      </div>

      <div class="col-xl-4 col-md-6 col-12 d-none d-xl-block">
        <div class="row border-bottom">
          <div class="col-5 pe-xl-0 px-lg-3 pe-md-0">
            <p>タグ名<br class="d-sm-none d-inline"><small>(タグ使用数)</small></p>
          </div>
          <div class="col-3 text-center px-0">
            <p>作成区分</p>
          </div>
          <div class="col-4 text-center px-0">
            <p>編集・削除</p>
          </div>
        </div>
      </div>

      <div class="col-xl-4 col-md-6 col-12 d-none d-md-block">
        <div class="row border-bottom">
          <div class="col-5 pe-xl-0 px-lg-3 pe-md-0">
            <p>タグ名<br class="d-sm-none d-inline"><small>(タグ使用数)</small></p>
          </div>
          <div class="col-3 text-center px-0">
            <p>作成区分</p>
          </div>
          <div class="col-4 text-center px-0">
            <p>編集・削除</p>
          </div>
        </div>
      </div>
    </div>
    <div class="row border-bottom mx-0">
      <% @tags.each do |tags| %>
        <div class="col-xl-4 col-md-6 col-12 me-0 mb-3">
          <div class="row">
            <div class="col-5 d-flex align-items-center">
              <%= link_to tags.tag_name,admin_tag_search_path(tag_id: tags.id), class:"text-break" %>
              <%= "(#{tags.writings.count})" %>
            </div>
            <div class="col-3 text-center d-flex align-items-center justify-content-center">
              <% if tags.admin_created %>
                <span class="text-danger">管理者</span>
              <% else %>
                <span class="text-success">会員</span>
              <% end %>
            </div>
            <div class="col-4 text-center">
              <%= link_to "編集", edit_admin_tag_path(tags.id), class: "text-dark" %></br>
              <%= link_to "削除", admin_tag_path(tags.id), method: :delete, data: { confirm: "本当に削除しますか？", cancel: "やめる", commit: "退会する"}, class: "text-dark" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>