config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'tags/index'
  end
  # TOPページ
  root to: 'public/homes#top'

  # ---会員側---
  # devise機能
  devise_for :members , controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :member do
    # ゲストログイン
    post '/member/guest_sign_in' => 'public/sessions#new_guest'
  end

  scope module: :public do
    # members
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    get "members/:id/unsubscribe" => 'members#unsubscribe', as: 'members_unsubscribe'
    # writings
    resources :writings do
      # get 'download'
      resource :writing_likes, only: [:create, :destroy]
      resources :writing_comments, only: [:create, :destroy]
    end
     # search(key_word)
    get 'search' => 'writings#word_search'
    # tags
    resources :tags do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end

  end
  # ------
  # ------

  # ---管理者側---
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # members
    resources :members, only: [:index, :show, :edit, :update]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    # writings
    resources :writings, only: [:index, :show, :update] do
      resources :writing_comments, only: [:destroy]
    end
    #  writing_comments
    resources :writing_comments, only: [:index]
    # search(key_word)
    get 'search' => 'writings#word_search'
    resources :tags, only: [:index, :edit, :create, :update, :destroy] do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end
  end
  # ------

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/writing.rb
class Writing < ApplicationRecord

  # --- association ---
  belongs_to :member
  belongs_to :trpg_rule
  has_many :writing_comments, dependent: :destroy
  has_many :writing_likes, dependent: :destroy

  has_many :writing_tags, dependent: :destroy
  has_many :tags, through: :writing_tags
  #-----------------

  # --- validation  ---
  validates :title, presence: { message: "タイトルを記入していません。"}, length: { minimum: 1, maximum: 30 }
  validates :summary, presence: false, length: { maximum: 50000 }
  validates :max_play_time, numericality: { only_integer: true, message: '数字を入力してください' }
  validates :min_play_time, numericality: { only_integer: true, message: '数字を入力してください' }
  validates :max_players, numericality: { only_integer: true, message: '数字を入力してください' }
  validates :max_players, numericality: { only_integer: true, message: '数字を入力してください' }
  #-----------------
  validate :validate_zip_file_mime_type
  #-----------------

  # --- Active Storage ---
  has_one_attached :writing_image
  has_one_attached :writing_zip
  #-----------------

  # --- scope ---
  # 公開・非公開機能
  scope :published, -> {where(is_public: true)}
  scope :unpublished, -> {where(is_public: false)}
  # ------

  # --- カスタムメソッド ---
  # 作品サムネイル画像のサイズ変更
  def get_thumbnail_image(width,height)
    unless writing_image.attached?
      file_path = Rails.root.join('app/assets/images/AdobeStock_301378170.jpeg')
      writing_image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    writing_image.variant(resize_to_limit: [width, height]).processed
  end

  # # アップロードデータ形式設定
  def validate_zip_file_mime_type
    return unless writing_zip.attached?
    if writing_zip.blob.content_type != 'application/zip'
      errors.add(:writing_zip, 'はZIP形式のファイルのみアップロードできます')
      writing_zip.purge # 非許可のファイルを削除する
    end
  end

  # 星レビュー機能
  def getPercent(number)
   if number.present?
     calPercent = number/5.to_f * 100
     percent = calPercent.round
     return percent.to_s
   else
     return 0
   end
  end

 # 最小最大判定
 def min_or_max

 end
  # 平均プレイ時間
  def avg_play_time
    (max_play_time + min_play_time)/2
  end

  # 平均プレイ人数

  # いいね機能
  def liked_by?(member)
    writing_likes.exists?(member_id: member.id)
  end

  # tag機能
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_writing_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_writing_tag
    end
  end

  # 検索機能
  def self.search(search_word)
    Writing.where("writings.title LIKE ? OR members.name LIKE ? OR trpg_rules.title LIKE ?", "%#{search_word}%", "%#{search_word}%", "%#{search_word}%")
  end
end

app/controllers/admin/writings_controller.rb
class Admin::WritingsController < ApplicationController
  # ログイン確認
  before_action :authenticate_admin!

  def index
    @writings = Writing.order(created_at: :desc).page(params[:page])
    @tag_list = Tag.left_joins(:writing_tags).group(:id).order('COUNT(writing_tags.tag_id) DESC').limit(10)
  end

  def show
    @writing = Writing.find(params[:id])
    @writing_tags = @writing.tags
    @tag_list = Tag.left_joins(:writing_tags).group(:id).order('COUNT(writing_tags.tag_id) DESC').limit(10)
    @comment_list = @writing.writing_comments.order(created_at: :desc).page(params[:page])
  end

  def update
    @writing = Writing.find(params[:id])

    if @writing.update(writing_params)
      flash[:notice] = "公開情報が更新されました。"
      redirect_to admin_writing_path(@writing.id)
    else
      @writing = Writing.find(params[:id])
      flash[:notice] = "公開情報の更新に失敗しました。"
      render :show
    end
  end

  def word_search
    @tag_list = Tag.left_joins(:writing_tags).group(:id).order('COUNT(writing_tags.tag_id) DESC').limit(10)
    keyword = params[:word]
    @writing_results = Writing.joins(:member, :trpg_rule).search(keyword)
    @writings = @writing_results.order(created_at: :desc).page(params[:page])
    if @writings.count > 0 && keyword.present?
      flash.now[:notice] = "「#{keyword}」の検索結果 - #{@writing_results.count}件"
    else
      flash[:alert] = "「#{keyword}」に該当する作品は見つかりませんでした。別の検索ワードをお試しください。"
      redirect_to admin_writings_path
    end
  end

  def tag_search
    @tag_list = Tag.left_joins(:writing_tags).group(:id).order('COUNT(writing_tags.tag_id) DESC').limit(10)
    @tag = Tag.find(params[:tag_id])
    @writing_results = @tag.writings.all
    @writings = @writing_results.order(created_at: :desc).page(params[:page])
    if @writings.count > 0
      flash.now[:notice] = "「#{@tag.tag_name}」の検索結果 - #{@writing_results.count}件"
    else
      flash[:alert] = "「#{@tag.tag_name}」に該当する作品は見つかりませんでした。別の検索タグをお試しください。"
      redirect_to admin_writings_path
    end
  end

  private

  def writing_params
    params.require(:writing).permit(:is_public)
  end
end

app/views/admin/writings/_comment.html.erb
<div class="row" id="comment">
  <h3>コメント<span><%= writing.writing_comments.count %><small>件</small></span></h3>
</div>
<!-- コメント一覧 -->
<% comment_list.each do |comment| %>
  <div class="row d-flex align-items-center shadow-sm">
    <div style="height: 40px;" class="col-md-2 col-auto text-center">
      <%= image_tag comment.member.get_profile_image(40,40), class:"border rounded-circle" %>
    </div>
    <div class="col-lg-8 col-md-7 col-sm-8 col-6">
      <p>
        <small><%= comment.member.name %></small></br>
        <span class="text-break"><%= comment.comment %></span></br>
        <small><span class="fw-light"><%= time_ago_in_words(comment.created_at) %>前</span></small>
      </p>
    </div>
    <div class="col-sm-2 col-3 px-sm-3 px-0 text-center">
      <%= link_to "削除", admin_writing_writing_comment_path(writing_id: writing.id,id: comment.id), method: :delete, class: "text-decoration-none link-dark" %>
    </div>
  </div>
<% end %>

app/views/admin/writings/_list.html.erb
<div class="table-responsive px-1 shadow-sm">
  <table class="table">
    <thead class="colgroup">
      <tr class="text-center text-nowrap">
        <th colspan="2" style="width: 24%" class="px-0">タイトル</th>
        <th style="width: 13.5%" class="px-0">作者名</th>
        <th style="width: 8.5%" class="px-0">人数</th>
        <th style="width: 9%" class="px-0">時間</th>
        <th style="width: 8%" class="px-0">難しさ</th>
        <th style="width: 7%" class="px-0">いいね！</th>
        <th style="width: 10.5%" class="px-0">タグ</th>
        <th style="width: 10%" class="px-0">公開ステータス</th>
        <th style="width: 9.5%" class="px-0">更新日</th>
      </tr>
    </thead>
    <% writings.each do |writings| %>
      <tbody class="text-nowrap">
        <tr>
          <td style="width: 8%">
            <%= link_to admin_writing_path(writings.id) do %>
              <%= image_tag writings.get_thumbnail_image(60,60), class:"border shadow-sm" %></br>
            <% end %>
          </td>
          <td class="align-middle ps-0">
              <span class="fw-light small">
                <%= writings.writing_type ? '【シナリオ】' : '【ルール】' %><%= truncate("#{writings.trpg_rule.title}", length: 8) %></br>
              </span>
            <%= link_to admin_writing_path(writings.id) do %>
              <span class="ps-2">
                <%= truncate("#{writings.title}", length: 12) %>
              </span>
            <% end %>
          </td>
          <td class="align-middle text-center px-0">
            <small><%= writings.member.name %></small>
          </td>
          <td class="align-middle text-center px-1">
            <%= writings.min_players %>~<%= writings.max_players %><small>人</small>
          </td>
          <td class="align-middle text-center px-1">
            <%= writings.min_play_time %>~<%= writings.max_play_time %><small>時間</small>
          </td>
          <td class="align-middle text-center px-1">
            <span class="star-rating">
              <span class="star-rating-front" style="width: <%= writings.getPercent(writings.difficulty) %>%;">★★★★★</span>
              <span class="star-rating-back">★★★★★</span>
            </span>
          </td>
          <td class="align-middle text-center">
            <%= writings.writing_likes.count %>
          </td>
          <td class="align-middle pe-1">
            <% writings.tags.each do |list| %>
              <%= list.tag_name %><br>
            <% end %>
          </td>
          <td class="align-middle text-center">
            <% if writings.is_public %>
              <span class="text-success fw-bold">公開中</span>
            <% else %>
              <span class="text-danger fw-bold">非公開</span>
            <% end %>
          </td>
          <td class="align-middle text-center px-0">
            <%= writings.updated_at.strftime('%Y/%m/%d') %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/admin/writings/_search.html.erb
<!-- ワード検索機能 -->
<div class="col-sm-8 col-12 px-0 mb-3">
  <%= form_with url: admin_search_path, local: true, method: :get, class:"col-10 input-group" do |f| %>
    <%= f.text_field :word, placeholder: "作品検索", class: "form-control" %>
    <%= f.button :submit, class: "btn btn-outline-success" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
  <% end %>
</div>
<!--タグ検索機能-->
<div class="col-sm-10 col-12 mb-3 py-1 border border-dark">
  <div class="row">
    <p class ="col">人気タグ</p>
    <%= link_to admin_tags_path, class: "col ml-auto text-end" do %>
      <span class="btn border btn-sm shadow-sm">タグ一覧へ</span>
    <% end %>
  </div>
  <div class="mb-2">
    <% tag_list.each do |tag| %>
      <span class="d-inline-block border p-1 me-1 mb-1">
        <%= link_to admin_tag_search_path(tag_id: tag.id), class:"text-nowrap text-black text-decoration-none" do %>
          <%= "#{tag.tag_name}(#{tag.writings.count})" %>
        <% end %>
      </span>
    <% end %>
  </div>
</div>

app/views/admin/writings/index.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <!-- 検索機能 -->
    <div class="row mx-0 justify-content-center">
      <%= render 'search', tag_list: @tag_list %>
    </div>
    <!-- 作品一覧 -->
    <div class="row my-3 mx-0 border-bottom border-dark border-2">
      <div class="col">
        <h1>作品<span class="fs-3 small d-none d-sm-inline">(シナリオ・ルール)</span>一覧</h1>
      </div>
    </div>
    <div class="row mx-0 mb-3">
      <%= render 'list', writings: @writings %>
    </div>
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= paginate(@writings) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/writings/show.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <!-- 検索機能 -->
    <div class="row mx-0 justify-content-center">
      <%= render 'search', tag_list: @tag_list %>
    </div>
    <!-- 作品詳細画面-->
    <div class="row my-3 mx-md-5 mx-0 border-bottom border-dark border-2 text-break">
      <h2 class="fw-bold"><%= @writing.title%><span class="fw-normal h4">の内容</span></h2>
    </div>
     <div class="row mx-md-5 mx-0 mb-5 flex-row">
      <div class="col-md-9 col-12 double-border p-3">
        <div class="row">
          <div class="col-md-3 col-sm-5 col-6 text-center px-0">
            <div class="row">
              <div class="col-12 mb-2">
                <%= image_tag @writing.get_thumbnail_image(120,120), class:"border shadow-sm" %>
              </div>
              <div class="col-12 mb-1">
                <% if @writing.writing_likes.exists? %>
                  <p class="mb-0">
                    <i class="fa-solid fa-heart fa-lg heart-color"></i> <%= @writing.writing_likes.count %> いいね
                  </p>
                  <% else %>
                  <p class="mb-0">
                    <i class="fa-solid fa-heart fa-lg text-secondary"></i> <%= @writing.writing_likes.count %> いいね
                  </p>
                <% end %>
              </div>
              <div class="col-12 px-0 mb-2">
                <% if @writing.writing_zip.present? %>
                  <%= link_to 'ダウンロード', rails_blob_path(@writing.writing_zip, disposition: "attachment"), class:"btn btn-sm btn-primary px-3" %>
                <% else %>
                  <button type="button" class="btn btn-sm btn-primary text-white-50 px-3" disabled="disabled">ダウンロード</button>
                <% end %>
              </div>
            </div>
          </div>
          <div class="col-sm-7 col-12 d-md-none my-2">
            <div class="row">
              <div class="col-auto mb-1">
                <%= image_tag @writing.member.get_profile_image(60,60), class:"border rounded-circle" %>
              </div>
              <div class="col-auto px-0">
                <span class="fs-5">
                  <%= @writing.member.name%></br>
                </span>
                <span class="small">
                  <%= link_to admin_member_path(@writing.member.id, anchor: "member_writings") do %>
                    他の作品を見る
                  <% end %>
                </span>
              </div>
            </div>
          </div>
          <div class="col-md-9 col-12">
            <div class="row">
              <div class="col-lg-4 col-md-5 col-sm-3 col-6 text-nowrap">
                タイトル：
              </div>
              <div class="col-lg-8 col-md-7 col-sm-9 col-6 ps-0 text-break">
                <%= @writing.title %>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-md-5 col-sm-3 col-6 text-nowrap">
                TRPGルール：
              </div>
              <div class="col-lg-8 col-md-7 col-sm-9 col-6 ps-0">
                <%= @writing.trpg_rule.title %>
              </div>
            </div>
            <div class="row d-flex">
              <div class="col-lg-4 col-md-5 col-sm-3 col-6 text-nowrap">
                <span class="small">シナリオ・ルール：</span>
              </div>
              <div class="col-auto ps-0">
                <%= @writing.writing_type ? 'シナリオ' : 'ルール'  %>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-md-5 col-sm-3 col-6 text-nowrap">
                想定人数：
              </div>
              <div class="col-auto ps-0">
                <%= @writing.min_players %> ~ <%= @writing.max_players %> 人
              </div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-md-5 col-sm-3 col-6 text-nowrap">
                想定時間：
              </div>
              <div class="col-auto ps-0">
                <%= @writing.min_play_time %> ~ <%= @writing.max_play_time %>時間
              </div>
            </div>
            <div class="row">
              <div class="col-lg-4 col-md-5 col-sm-3 col-6 text-nowrap">
                想定難易度：
              </div>
              <div class="col-sm-auto col-12 text-center ps-0">
                簡単
                <span class="star-rating">
                  <span class="star-rating-front" style="width: <%= @writing.getPercent(@writing.difficulty) %>%;">★★★★★</span>
                  <span class="star-rating-back">★★★★★</span>
                </span>
                難しい
              </div>
            </div>
            <!--タグ欄-->
            <div class="row">
              <div class="col mt-3 py-1">
                <% if @writing_tags.present? %>
                  <% @writing_tags.each do |tag| %>
                    <span class="d-inline-block border p-1 me-1 mb-1">
                      <%= link_to admin_tag_search_path(tag_id: tag.id), class:"text-black text-decoration-none" do %>
                        <%= "#{tag.tag_name}(#{tag.writings.count})" %>
                      <% end %>
                    </span>
                  <% end %>
                <% end%>
              </div>
            </div>
            <div class="row mt-4 justify-content-end">
              <div class="col-auto text-end text-nowrap">
              <small>
                更新日：<%= @writing.updated_at.strftime('%Y年%m月%d日 %H:%M')%>
              </small>
              </div>
            </div>
          </div>
        </div>
        <!---->
        <!-- 概要 -->
        <div class="row my-3 py-2 border-top border-bottom border-dark">
          <p class="mb-2">概要：</p>
          <p>
            <%= safe_join(@writing.summary.split("\n"),tag(:br)) %>
          </p>
        </div>
        <%= form_with model: @writing, url: admin_writing_path(@writing.id), method: :patch, class:"row justify-content-end me-2" do |f| %>
          <div class="col-auto">
          <%= f.select :is_public, [['公開',true],['非公開',false]], {}, class:"form-select border-dark" %>
          </div>
          <%= f.submit "公開情報を更新", class: "col-auto btn btn-outline-primary fw-bold" %>
        <% end %>
      </div>
      <div class="d-none d-md-block col-md-3 col-12 ps-3 pe-0 border">
        <div class="row mx-0 ms-xl-4 pt-3 px-1 pb-5 border border-dark">
          <!-- ユーザー情報 PCサイズ -->
          <div class="text-center mb-1">
            <%= image_tag @writing.member.get_profile_image(50,50), class:"border rounded-circle" %>
          </div>
          <div class="text-center px-0">
            <span class="small">
              <%= @writing.member.name%></br>
              <%= link_to "他の作品を見る", admin_member_path(@writing.member.id, anchor: "member_writings") %>
            </span>
          </div>
        </div>
      </div>
    </div>
    <!-- コメント欄 -->
    <div class="row mx-md-5 mx-0 mb-5">
      <div class="col-md-9 col-12 p-3 border border-dark">
        <%= render 'comment', writing: @writing, comment_list: @comment_list %>
        <div class="row justify-content-center mt-3">
          <div class="col-auto">
            <%= paginate @comment_list %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/writings/tag_search.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <!-- 検索機能 -->
    <div class="row mx-0 justify-content-center">
      <%= render 'search', tag_list: @tag_list %>
    </div>
    <!-- 作品一覧 -->
   <div class="row my-3 mx-0 border-bottom border-dark border-2">
      <div class="col">
        <h1>作品<span class="fs-3 small d-none d-sm-inline">(シナリオ・ルール)</span>一覧</h1>
      </div>
    </div>
    <div class="row mx-0">
      <%= render 'list', writings: @writings %>
    </div>
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= paginate(@writings) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/writings/word_search.html.erb
<div class="row my-5 justify-content-center">
  <div class="col-xl-11 col-12">
    <!-- 検索機能 -->
    <div class="row mx-0 justify-content-center">
      <%= render 'search', tag_list: @tag_list %>
    </div>
    <!-- 作品一覧 -->
    <div class="row my-3 mx-0 border-bottom border-dark border-2">
      <div class="col">
        <h1>作品<span class="fs-3 small d-none d-sm-inline">(シナリオ・ルール)</span>一覧</h1>
      </div>
    </div>
    <div class="row mx-0">
      <%= render 'list', writings: @writings %>
    </div>
    <div class="row justify-content-center">
      <div class="col-auto">
        <%= paginate(@writings) %>
      </div>
    </div>
  </div>
</div>