config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'tags/index'
  end
  # TOPページ
  root to: 'public/homes#top'

  # ---会員側---
  # devise機能
  devise_for :members , controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :member do
    # ゲストログイン
    post '/member/guest_sign_in' => 'public/sessions#new_guest'
  end

  scope module: :public do
    # members
    resources :members, only: [:index, :show, :edit, :update, :destroy]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    get "members/:id/unsubscribe" => 'members#unsubscribe', as: 'members_unsubscribe'
    # writings
    resources :writings do
      # get 'download'
      resource :writing_likes, only: [:create, :destroy]
      resources :writing_comments, only: [:create, :destroy]
    end
     # search(key_word)
    get 'search' => 'writings#word_search'
    # tags
    resources :tags do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end

  end
  # ------
  # ------

  # ---管理者側---
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    # members
    resources :members, only: [:index, :show, :edit, :update]
    get "members/:id/writings" => 'members#writings', as: 'member_writings'
    get "members/:id/like_writings" => 'members#like_writings', as: 'member_like_writings'
    # writings
    resources :writings, only: [:index, :show, :update] do
      resources :writing_comments, only: [:destroy]
    end
    #  writing_comments
    resources :writing_comments, only: [:index]
    # search(key_word)
    get 'search' => 'writings#word_search'
    resources :tags, only: [:index, :edit, :create, :update, :destroy] do
      # search(tag)
      get 'writings' => 'writings#tag_search', as: 'search'
    end
  end
  # ------

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500&display=swap" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ヘッダー -->
    <header>
      <nav class="navbar navbar-expand-lg py-0" style="background-color: #e3f2fd;">
        <div class="container-fluid">
          <!-- ロゴマーク -->
          <%= link_to root_path, class:"navbar-brand mx-5 mx-sm-3" do %>
            <span class="justify-content-center">
              <%= image_tag 'TRPG Writing Lab.png', size: "200x90" %>
            </span>
          <% end %>
          <!-- ログインメッセージ -->
          <div class="nav-item ps-3 my-1 me-sm-3 me-0">
            <span class="align-middle">
              <% if member_signed_in? %>
                ようこそ、<br class="d-xl-none d-sm-none d-lg-inline d-inline"><%= current_member.name %>さん！
              <% elsif admin_signed_in? %>
                管理者として<br class="d-xl-none d-sm-none d-lg-inline d-inline">ログインしています。
              <% end %>
            </span>
          </div>
          <!-- ナビゲーションメニュー -->
          <button class="navbar-toggler ms-auto my-1" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggler">
            <!-- 会員側 -->
            <% if member_signed_in? %>
            <div class="ms-3">
              <ul class="navbar-nav justify-content-between text-nowrap">
                <li class="nav-item me-4">
                  <%= link_to "メンバー", members_path, class:"nav-link" %>
                </li>
                <li class="nav-item me-4">
                  <%= link_to writings_path, class:"nav-link" do %>
                    作品<span class="small">(シナリオ・ルール)</span>
                  <% end %>
                </li>
                <li class="nav-item me-4">
                  <%= link_to "タグ", tags_path, class:"nav-link" %>
                </li>
              </ul>
            </div>
            <ul class="navbar-nav custom-nav-border py-3 ps-3 ms-auto text-nowrap">
              <li class="nav-item">
                <%= link_to "マイページ", member_path(current_member.id), class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class:"nav-link" %>
              </li>
            </ul>
            <!-- 管理者 -->
            <% elsif admin_signed_in? %>
            <div class="ms-3">
              <ul class="navbar-nav justify-content-between text-nowrap">
                <li class="nav-item me-2">
                  <%= link_to "メンバー", admin_members_path, class:"nav-link" %>
                </li>
                <li class="nav-item me-2">
                  <%= link_to admin_writings_path, class:"nav-link" do %>
                    作品<span class="small">(シナリオ・ルール)</span>
                  <% end %>
                </li>
                <li class="nav-item me-2">
                  <%= link_to "タグ", admin_tags_path, class:"nav-link" %>
                </li>
                <li class="nav-item me-2">
                  <%= link_to "コメント", admin_writing_comments_path, class:"nav-link" %>
                </li>
              </ul>
            </div>
            <ul class="navbar-nav custom-nav-border text-nowrap py-3 ps-3 ms-auto">
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link" %>
              </li>
            </ul>
            <!-- ログアウト時 -->
            <% else %>
            <div class="w-50 ms-3 me-auto">
              <ul class="navbar-nav justify-content-between text-nowrap">
                <li class="nav-item">
                  <%= link_to "アカウントを作成", new_member_registration_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_member_session_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ゲストログイン", member_guest_sign_in_path, method: :post, class:"nav-link" %>
                </li>
              </ul>
            </div>
            <% end %>
          </div>
        </div>
      </nav>
      <div class="mb-3">
       <%= render "layouts/flash" %>
      </div>
    </header>
    <!-- メイン -->
    <main class="container-lg container-fluid">
      <%= yield %>
    </main>
    <!-- フッター -->
    <footer></footer>
  </body>
</html>